edition                       = "2018"
newline_style                 = "Unix"
unstable_features             = true

max_width                     = 140
hard_tabs                     = false
tab_spaces                    = 2
blank_lines_upper_bound       = 2
enum_discrim_align_threshold  = 20
struct_field_align_threshold  = 20

comment_width                 = 80
wrap_comments                 = true
normalize_comments            = true
normalize_doc_attributes      = true

brace_style                   = "SameLineWhere"
control_brace_style           = "AlwaysSameLine"
indent_style                  = "Block"
force_multiline_blocks        = false
empty_item_single_line        = true
overflow_delimited_expr       = true
struct_lit_single_line        = false

fn_args_layout                = "Tall"
fn_single_line                = false

imports_indent                = "Block"
imports_layout                = "HorizontalVertical"
imports_granularity           = "Crate"
reorder_imports               = true
group_imports                 = "StdExternalCrate"

reorder_modules               = true

binop_separator               = "Front"
space_after_colon             = true
space_before_colon            = false
spaces_around_ranges          = false
type_punctuation_density      = "Wide"

condense_wildcard_suffixes    = true
hex_literal_case              = "Lower"
remove_nested_parens          = true

error_on_line_overflow        = true
error_on_unformatted          = true

format_code_in_doc_comments   = true
format_generated_files        = false
format_macro_matchers         = true
format_macro_bodies           = true
format_strings                = true

match_arm_blocks              = true
match_arm_leading_pipes       = "Never"
match_block_trailing_comma    = true

merge_derives                 = true
reorder_impl_items            = true

trailing_comma                = "Vertical"
trailing_semicolon            = true

report_fixme                  = "Always"
report_todo                   = "Always"

use_field_init_shorthand      = true
use_try_shorthand             = true
